<?php
return [
  'mosaico_layout' => [
    'group_name' => 'Mosaico Preferences',
    'group' => 'mosaico',
    'name' => 'mosaico_layout',
    'quick_form_type' => 'Select',
    'type' => 'String',
    'html_type' => 'select',
    'html_attributes' => [
      'class' => 'crm-select2',
    ],
    'pseudoconstant' => [
      'callback' => 'CRM_Mosaico_Utils::getLayoutOptions',
    ],
    'default' => 'auto',
    'add' => '4.7',
    'title' => 'Mosaico editor layout',
    'is_domain' => 1,
    'is_contact' => 0,
    'description' => NULL,
    'help_text' => NULL,
  ],
  'mosaico_graphics' => [
    'group_name' => 'Mosaico Preferences',
    'group' => 'mosaico',
    'name' => 'mosaico_graphics',
    'quick_form_type' => 'Select',
    'type' => 'String',
    'html_type' => 'select',
    'html_attributes' => [
      'class' => 'crm-select2',
    ],
    'pseudoconstant' => [
      'callback' => 'CRM_Mosaico_Utils::getGraphicsOptions',
    ],
    'default' => 'auto',
    'add' => '4.7',
    'title' => 'Mosaico graphics driver',
    'is_domain' => 1,
    'is_contact' => 0,
    'description' => NULL,
    'help_text' => NULL,
  ],
  'mosaico_scale_factor1' => [
    'group_name' => 'Mosaico Preferences',
    'group' => 'mosaico',
    'name' => 'mosaico_scale_factor1',
    'quick_form_type' => 'Select',
    'type' => 'String',
    'html_type' => 'select',
    'html_attributes' => [
      'class' => 'crm-select2',
    ],
    'pseudoconstant' => [
      'callback' => 'CRM_Mosaico_Utils::getResizeScaleFactor',
    ],
    'default' => '',
    'add' => '5.24',
    'title' => 'Image resize scale factor',
    'is_domain' => 1,
    'is_contact' => 0,
    'description' => NULL,
    'help_text' => NULL,
  ],
  'mosaico_scale_factor2' => [
    'group_name' => 'Mosaico Preferences',
    'group' => 'mosaico',
    'name' => 'mosaico_scale_factor2',
    'quick_form_type' => 'Select',
    'type' => 'String',
    'html_type' => 'select',
    'html_attributes' => [
      'class' => 'crm-select2',
    ],
    'pseudoconstant' => [
      'callback' => 'CRM_Mosaico_Utils::getResizeScaleFactor',
    ],
    'default' => '',
    'add' => '5.24',
    'title' => 'Image resize scale factor',
    'is_domain' => 1,
    'is_contact' => 0,
    'description' => NULL,
    'help_text' => NULL,
  ],
  'mosaico_scale_width_limit1' => [
    'group_name' => 'Mosaico Preferences',
    'group' => 'mosaico',
    'name' => 'mosaico_scale_width_limit1',
    'quick_form_type' => 'Select',
    'type' => 'String',
    'html_type' => 'select',
    'html_attributes' => [
      'class' => 'crm-select2',
    ],
    'pseudoconstant' => [
      'callback' => 'CRM_Mosaico_Utils::getResizeScaleWidthLimit',
    ],
    'default' => '',
    'add' => '5.24',
    'title' => 'Image resize scale factor width limit',
    'is_domain' => 1,
    'is_contact' => 0,
    'description' => NULL,
    'help_text' => NULL,
  ],
  'mosaico_scale_width_limit2' => [
    'group_name' => 'Mosaico Preferences',
    'group' => 'mosaico',
    'name' => 'mosaico_scale_width_limit2',
    'quick_form_type' => 'Select',
    'type' => 'String',
    'html_type' => 'select',
    'html_attributes' => [
      'class' => 'crm-select2',
    ],
    'pseudoconstant' => [
      'callback' => 'CRM_Mosaico_Utils::getResizeScaleWidthLimit',
    ],
    'default' => '',
    'add' => '5.24',
    'title' => 'Image resize scale factor width limit',
    'is_domain' => 1,
    'is_contact' => 0,
    'description' => NULL,
    'help_text' => NULL,
  ],
  'mosaico_custom_templates_dir' => [
    'group_name' => 'Mosaico Preferences',
    'group' => 'mosaico',
    'name' => 'mosaico_custom_templates_dir',
    'quick_form_type' => 'Element',
    'type' => 'String',
    'html_type' => 'text',
    'default' => '[civicrm.files]/mosaico_tpl',
    'add' => '4.7',
    'title' => 'Mosaico Custom Templates Directory',
    'is_domain' => 1,
    'is_contact' => 0,
    'description' => NULL,
    'help_text' => NULL,
  ],
  'mosaico_custom_templates_url' => [
    'group_name' => 'Mosaico Preferences',
    'group' => 'mosaico',
    'name' => 'mosaico_custom_templates_url',
    'quick_form_type' => 'Element',
    'type' => 'String',
    'html_type' => 'text',
    'default' => '[civicrm.files]/mosaico_tpl',
    'add' => '4.7',
    'title' => 'Mosaico Custom Templates URL',
    'is_domain' => 1,
    'is_contact' => 0,
    'description' => NULL,
    'help_text' => NULL,
  ],
];
